### ISSUE TITLE
DocxToPdf closing opened Word documents.

### ISSUE THREAD

**Issue by allanjonis** [AlJohri/docx2pdf#36]
I have here one automation application on windows desktop using docx, works well on conversion, except the case this close all word windows on GUI when conversion start.
 Someone find one way to solve this?
 Thanks.

**Comment by AlJohri** [comment]
@allanjonis I think because this library relies on Word itself to do the conversion it may hide the GUI at start and close the GUI at the end. There is a `--keep-active` option to prevent it closing at the end.

I don't think actively using Word while the conversion is occurring would be the best idea. Is that what you're trying to do?

**Comment by allanjonis** [comment]
@AlJohri Thanks for your reply, yes I have a small application running on the end user's desktop and sometimes the user opens some Word file.
    Worked short time ago commenting lines 37 and 38 in the __init__.py file, avoiding the word process ended, so far it works fine.
